### ISSUE TITLE
Input tensor size 

### ISSUE THREAD

**Issue by StonERMax** [jackaduma/CycleGAN-VC3#2]
Would you release the preprocess code ASAP? What is the input size of the preprocessed audio tensor? The paper says that the feature dimension increased from 35 to 80 and a training sample consisted of randomly cropped 64 frames. According to the paper, the input size is [1, 80, 64], but the generator gets the input and changes it size to 2304 in the first time. The input size can not match the 2304.

**Comment by jackaduma** [comment]
Thanks for following. 
我用中文回答吧，“a training sample consisted of randomly cropped 64 frames” 的意思不是 输入size 是 80*64
是对音频文件截取64帧进行melspec的提取，具体size 我稍后回复你

**Comment by jackaduma** [comment]
论文实验部分：
Following the study of MelGAN [39], which we used as a vocoder in our experiments, we
extracted an 80-dimensional log mel-spectrogram with a window length of 1024 and hop length of 256 samples.

我最近没时间看MelGAN，后续会进行更新，谢谢你的关注

**Comment by StonERMax** [comment]
能具体说一下处理的方法（或者代码嘛）具体的size是多少呢

**Comment by StonERMax** [comment]
还有事TF2D的输入需要source，但输入的source是1D的，要将1D转变为2D吧，我看了代码里TF2D module这一块没有这个部分，论文也没有，这个也可以说一下嘛

**Comment by jackaduma** [comment]
> 还有事TF2D的输入需要source，但输入的source是1D的，要将1D转变为2D吧，我看了代码里TF2D module这一块没有这个部分，论文也没有，这个也可以说一下嘛

这部分 我更新了，

**Comment by StonERMax** [comment]
谢谢！input的处理，我随机提取64帧，最终得到的size还是[80,64]，不知道你还记不记得输入的size是多少

**Comment by jackaduma** [comment]
> 谢谢！input的处理，我随机提取64帧，最终得到的size还是[80,64]，不知道你还记不记得输入的size是多少
这部分不是我记得不记得😂，我还没实现呢， 你说的问题，按照vc2的网络架构，我试了，确实存在问题，我要看下是否修改网络，还是特征提取部分有什么tricks
I will update my work ASAP
Thanks

**Comment by jackaduma** [comment]
这部分不是我记得不记得😂，我还没实现呢， 你说的问题，按照vc2的网络架构，我试了，确实存在问题，我要看下是否修改网络，还是特征提取部分有什么tricks
I will update my work ASAP
Thanks

**Comment by StonERMax** [comment]
网络的部分，我按照论文的特征提取出的tensor，把代码部分改了一下，可以跑。如果需要，我们可以交流

**Comment by jackaduma** [comment]
ok  你是用我修改后的 TF结构吗，这部分ok吗
如果可以 你可以贡献在这个项目吗 我把你加在contribute里，
